const config = {
  url: 'https://api.tsitskun.tk',
  login: 'https://api.tsitskun.tk/signin',
  signup: 'https://api.tsitskun.tk/signup',
  logout: 'https://api.tsitskun.tk/logout',
  getUser: 'https://api.tsitskun.tk/users/me',
  git: 'https://api.github.com/repos/derYpsilon/news-explorer-front/commits',
  maxGitCommits: 15,
  month: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа',
    'сентября', 'октября', 'ноября', 'декабря'],
  newsFeed: 'https://newsapi.org/v2/everything?sortBy=popularity&apiKey=61e9a15929844de49c00be490b903f34&language=ru&pageSize=100',
  showMore: { node: '#show-more', hide: 'results__button_hide' },
  showStep: 3,
  cardSample: '#card-sample',
  card: {
    node: '.card',
    img: '.card__pic',
    date: '.card__date',
    title: '.card__title',
    text: '.card__text',
    src: '.card__src',
    warning: '.card__warning',
    icon: { node: '.card__icon', logged: 'card__icon_logged', marked: 'card__icon_marked' },
  },
  resultsField: '.results__news',
  newsForm: 'news-finder',
  newsFormSearchField: 'search',
  preloader: { node: '#preloader-searching', hide: 'preloader__message_hide' },
  notFound: { node: '#preloader-not-found', hide: 'preloader__message_hide' },
  serverError: { node: '#preloader-server-error', hide: 'preloader__message_hide' },
  resultsSection: { node: '.results', hide: 'results_hide' },
}

export default config
